---
- hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install nginx web server for ubuntu
      shell: "apt-get update && add-apt-repository ppa:deadsnakes/ppa"
      become: yes

    - name: Install python 3
      apt:
        name: python3.8
        state: latest

    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: true

    - name: Copy nginx config files
      copy:
        src: "./files/nginx.conf"
        dest: "/etc/nginx/nginx.conf"
        mode: 0644

    - name: Creates directory
      file: 
        path: "/var/www/localhost"
        state: directory

    - name: Copy static files
      copy:
        src: "./files/static_website/"
        dest: "/var/www/localhost/"
        mode: 0644

    - name: Update static nginx config
      copy: 
        src: "./files/static_website.conf"
        dest: "/etc/nginx/conf.d/localhost.conf"
        mode: 0644
      
    - name: Start Nginx
      service: name=nginx state=stopped 
      become: yes