---
- hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  
  tasks:
          - name: Update apt repo and cache on all Debian/Ubuntu boxes
            apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
          
          - name: Upgrade all packages on servers
            apt: upgrade=dist force_apt_get=yes
          
          - name: Add hostname to hostfile
            shell: "echo \"127.0.0.1 $(hostname)\" >> /etc/hosts"
          
          - name: Install prerequisites
            apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
            loop: [ 'aptitude' ]
          
          - name: Add PPA for Nginx.
            apt_repository:
#            repo: 'ppa:deadsnakes/ppa'
             repo: 'ppa:nginx/stable'
             state: present
             update_cache: true
          
          - name: Install nginx
            apt: name=nginx update_cache=yes state=latest
        
          - name: Test for running nginx
            shell: ps axuf | grep 'nginx' | grep -v "grep" | tr -d "\n" | cat
            register: test_running_nginx
            changed_when: False
            tags: restart-nginx
    
          - name: First check the configuration
            shell: /usr/sbin/nginx -t
            register: test_nginx_config
            when: test_running_nginx.stdout != ""
            changed_when: False
            ignore_errors: True
            tags: restart-nginx
          
          - name: Reload Nginx
            #service: name=nginx state=reloaded
            shell: "/etc/init.d/nginx reloaded"
            when: test_running_nginx.stdout != "" and test_nginx_config.rc == 0
            tags: restart-nginx
          
          - name: Restart Nginx
            #service: name=nginx state=restarted
            shell: "/etc/init.d/nginx reloaded"
            when: test_running_nginx.stdout != "" and test_nginx_config.rc == 0
            tags: restart-nginx

